name: Runs Shell Script

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  shell-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./run.sh

      - name: Run Shell Script
        run: ./run.sh


